# Generated by Django 4.1.6 on 2023-05-22 17:11

from django.db import migrations

def populate_db(apps, schema_editor):
    Redirect = apps.get_model('shortener', 'Redirect')

class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
